app:
  name: ""
  version: ""
http:
  url: ""
  port: ""
sqlite:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false